"""
registry.py — AUTO-GENERATED by config/generate.py
DO NOT EDIT MANUALLY. Edit config/workflow_config.json and re-run generate.py.
"""

from __future__ import annotations

from typing import Any


STEP_CONFIG: dict[str, dict[str, Any]] = {
    "STEP_00": {
        "name": "Input Parser",
        "plan_file": "step_00_input_parser.md",
        "tools": ["parse_predicted_conditions", "parse_manifest"],
        "substeps": [
                {
                        "id": "0.1",
                        "name": "Parse predicted conditions",
                        "tools": [
                                "parse_predicted_conditions"
                        ]
                },
                {
                        "id": "0.2",
                        "name": "Parse manifest",
                        "tools": [
                                "parse_manifest"
                        ]
                },
                {
                        "id": "0.3",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_01": {
        "name": "Specification Evaluator",
        "plan_file": "step_01_evaluate.md",
        "tools": ["evaluate_specifications"],
        "substeps": [
                {
                        "id": "1.1",
                        "name": "Evaluate all document requests against manifest",
                        "tools": [
                                "evaluate_specifications"
                        ]
                },
                {
                        "id": "1.2",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
    "STEP_02": {
        "name": "Output Generator",
        "plan_file": "step_02_output.md",
        "tools": ["generate_final_output"],
        "substeps": [
                {
                        "id": "2.1",
                        "name": "Generate final output",
                        "tools": [
                                "generate_final_output"
                        ]
                },
                {
                        "id": "2.2",
                        "name": "Save step report",
                        "tools": [
                                "save_step_report"
                        ]
                }
        ],
    },
}

STEP_ORDER: list[str] = ["STEP_00", "STEP_01", "STEP_02"]
GENERAL_TOOL_NAMES: list[str] = ["save_step_report", "get_workflow_status"]


def get_step_tools(step_id: str) -> list[str]:
    return STEP_CONFIG.get(step_id, {}).get("tools", [])


def get_step_plan_file(step_id: str) -> str | None:
    return STEP_CONFIG.get(step_id, {}).get("plan_file")


def get_current_step(state: dict) -> str | None:
    return state.get("current_step")
