#!/usr/bin/env python3
"""
Generate registry.py from workflow_config.json.

Run from the project root:
    python3 config/generate.py
"""

import json
import textwrap
from pathlib import Path

CONFIG_PATH = Path(__file__).parent / "workflow_config.json"
OUTPUT_PATH = Path(__file__).parent.parent / "registry.py"


def load_config() -> dict:
    with open(CONFIG_PATH) as f:
        return json.load(f)


def build_step_order(config: dict) -> list[str]:
    phases = sorted(config["phases"].items(), key=lambda kv: kv[1]["order"])
    order = []
    for _phase_name, phase in phases:
        for step_num in phase["steps"]:
            order.append(f"STEP_{step_num:02d}")
    return order


def render_registry(config: dict) -> str:
    step_order = build_step_order(config)
    general_tools = config["general_tools"]

    lines = [
        '"""',
        "registry.py — AUTO-GENERATED by config/generate.py",
        "DO NOT EDIT MANUALLY. Edit config/workflow_config.json and re-run generate.py.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "",
        "STEP_CONFIG: dict[str, dict[str, Any]] = {",
    ]

    for step_id, step in config["steps"].items():
        substeps_repr = json.dumps(step["substeps"], indent=8)
        substeps_indented = textwrap.indent(substeps_repr, "        ")
        seen: set[str] = set()
        step_tools: list[str] = []
        for sub in step["substeps"]:
            for t in sub.get("tools", []):
                if t not in seen and t not in general_tools:
                    seen.add(t)
                    step_tools.append(t)

        lines.append(f'    "{step_id}": {{')
        lines.append(f'        "name": {json.dumps(step["name"])},')
        lines.append(f'        "plan_file": {json.dumps(step["plan_file"])},')
        lines.append(f'        "tools": {json.dumps(step_tools)},')
        lines.append(f'        "substeps": {substeps_indented.strip()},')
        lines.append("    },")

    lines += [
        "}",
        "",
        f"STEP_ORDER: list[str] = {json.dumps(step_order)}",
        f"GENERAL_TOOL_NAMES: list[str] = {json.dumps(general_tools)}",
        "",
        "",
        "def get_step_tools(step_id: str) -> list[str]:",
        "    return STEP_CONFIG.get(step_id, {}).get(\"tools\", [])",
        "",
        "",
        "def get_step_plan_file(step_id: str) -> str | None:",
        "    return STEP_CONFIG.get(step_id, {}).get(\"plan_file\")",
        "",
        "",
        "def get_current_step(state: dict) -> str | None:",
        '    return state.get("current_step")',
    ]

    return "\n".join(lines) + "\n"


def main() -> None:
    config = load_config()
    content = render_registry(config)
    OUTPUT_PATH.write_text(content)
    print(f"Generated: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
